-- Generated by scripts/audit-salon-categories.mjs
-- City: الخبر
-- Rows: 22
BEGIN;
UPDATE public.businesses SET category_value = 'salon' WHERE id = '78546f7e-fa3b-40af-a849-0ded49a8ca2f' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'a1d4eeb1-89c8-4a3c-b12b-dc7d6c7a79c4' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '375927b3-9e22-40aa-87d4-695aa56ae030' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '3ee48a4f-9131-4abd-9557-6ed55fade04d' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '4d9923df-ad91-4040-bb88-6a22b099eef3' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '49d29ddb-f412-41d1-9ec7-3d5aa085f51b' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '840cfa42-050d-4752-a377-735658a843da' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'f71a70e4-d618-4f78-90f8-ad37e904d509' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'cedb336d-2729-4dda-95ff-4ebd187d72ec' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '09e1e94f-5246-4302-b660-807bfe90f593' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '5a1e84f6-1565-4c59-872e-e0db306086a6' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '1866de55-58ec-4d93-af52-39bfcc4b6bd7' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '6e58689c-873c-46cb-8b1c-c0f6afbe511a' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '2dc82258-16be-4afb-b288-6c29a9b7276b' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'f5ded778-6ed8-4746-9508-b0c82a6b359d' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'c5b8db22-95e4-49d2-90bb-7492cb3724be' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'ce6786d2-e791-49e1-bbdb-e917dd91d0ef' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '357c5a33-d12c-4341-87fe-c62688d496dd' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'c7df4404-f975-4d21-b052-a2bc85b55dd0' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '7a737927-743b-43ea-99be-ed3566073fed' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = 'b147bd78-9a2e-4bf9-830b-b94977c06304' AND COALESCE(category_value,'') <> 'salon';
UPDATE public.businesses SET category_value = 'salon' WHERE id = '55d1915a-c616-410d-94c6-c495e855b314' AND COALESCE(category_value,'') <> 'salon';
COMMIT;
